// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelRecommendation.Infrastructure.Persistence;

#nullable disable

namespace TravelRecommendation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    partial class TravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.ApiCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RequestKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestKey");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Action", "RequestKey")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiCaches_Provider_Action_RequestKey");

                    b.ToTable("ApiCaches", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Attractions", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Beach destinations",
                            Name = "Beach",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nature destinations",
                            Name = "Nature",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cultural destinations",
                            Name = "Culture",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Historical destinations",
                            Name = "History",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Food-focused destinations",
                            Name = "Food",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Nightlife destinations",
                            Name = "Nightlife",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Adventure destinations",
                            Name = "Adventure",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Relaxation destinations",
                            Name = "Relaxation",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mountain destinations",
                            Name = "Mountains",
                            Type = "Interest"
                        },
                        new
                        {
                            Id = 10,
                            Description = "City break destinations",
                            Name = "City Break",
                            Type = "TripStyle"
                        });
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageDailyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Climate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Popularity")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Country", "City");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.DestinationCategory", b =>
                {
                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DestinationCategories", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.DestinationInterest", b =>
                {
                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("DestinationId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("DestinationInterests", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId", "DestinationId")
                        .IsUnique();

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Interests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Beaches and coastal destinations",
                            Name = "Beach"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nature and outdoor experiences",
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Culture and local traditions",
                            Name = "Culture"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Historical sites and heritage",
                            Name = "History"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Food and gastronomy",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Nightlife and entertainment",
                            Name = "Nightlife"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Adventure and extreme activities",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Relaxation and wellness",
                            Name = "Relaxation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mountain destinations",
                            Name = "Mountains"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Shopping and markets",
                            Name = "Shopping"
                        });
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalQuery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("Recommendations", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.RecommendationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("RecommendationId", "DestinationId")
                        .IsUnique();

                    b.HasIndex("RecommendationId", "Rank")
                        .IsUnique();

                    b.ToTable("RecommendationItems", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator role",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard user role",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelHistories", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DestinationId");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("TravelItineraries", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItineraryDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TravelItineraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelItineraryId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TravelItineraryDays", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItineraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("AttractionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TravelItineraryDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("TravelItineraryDayId", "Order")
                        .IsUnique();

                    b.ToTable("TravelItineraryItems", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MinTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PreferredClimate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TravelPeriod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.UserPreferenceInterest", b =>
                {
                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("UserPreferenceId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserPreferenceInterests", (string)null);
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Activity", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.ApiCache", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.User", "User")
                        .WithMany("ApiCaches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("Attractions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.DestinationCategory", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Category", "Category")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("DestinationCategories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.DestinationInterest", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("DestinationInterests")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.Interest", "Interest")
                        .WithMany("DestinationInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Interest");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("Favorites")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelRecommendation.Domain.Entities.UserPreference", "UserPreference")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserPreference");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.RecommendationItem", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("RecommendationItems")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("RecommendationItems")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelHistory", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("TravelHistories")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.User", "User")
                        .WithMany("TravelHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItinerary", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Destination", "Destination")
                        .WithMany("TravelItineraries")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("TravelItineraries")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelRecommendation.Domain.Entities.User", "User")
                        .WithMany("TravelItineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.UserPreference", "UserPreference")
                        .WithMany("TravelItineraries")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Destination");

                    b.Navigation("Recommendation");

                    b.Navigation("User");

                    b.Navigation("UserPreference");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItineraryDay", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.TravelItinerary", "TravelItinerary")
                        .WithMany("Days")
                        .HasForeignKey("TravelItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelItinerary");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItineraryItem", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelRecommendation.Domain.Entities.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelRecommendation.Domain.Entities.TravelItineraryDay", "TravelItineraryDay")
                        .WithMany("Items")
                        .HasForeignKey("TravelItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Attraction");

                    b.Navigation("TravelItineraryDay");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.User", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.UserPreferenceInterest", b =>
                {
                    b.HasOne("TravelRecommendation.Domain.Entities.Interest", "Interest")
                        .WithMany("UserPreferenceInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelRecommendation.Domain.Entities.UserPreference", "UserPreference")
                        .WithMany("UserPreferenceInterests")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("UserPreference");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Category", b =>
                {
                    b.Navigation("DestinationCategories");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Attractions");

                    b.Navigation("DestinationCategories");

                    b.Navigation("DestinationInterests");

                    b.Navigation("Favorites");

                    b.Navigation("RecommendationItems");

                    b.Navigation("TravelHistories");

                    b.Navigation("TravelItineraries");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Interest", b =>
                {
                    b.Navigation("DestinationInterests");

                    b.Navigation("UserPreferenceInterests");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Recommendation", b =>
                {
                    b.Navigation("RecommendationItems");

                    b.Navigation("TravelItineraries");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItinerary", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.TravelItineraryDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.User", b =>
                {
                    b.Navigation("ApiCaches");

                    b.Navigation("Favorites");

                    b.Navigation("Recommendations");

                    b.Navigation("TravelHistories");

                    b.Navigation("TravelItineraries");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("TravelRecommendation.Domain.Entities.UserPreference", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("TravelItineraries");

                    b.Navigation("UserPreferenceInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
