import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { EMPTY, switchMap } from 'rxjs';
import {
  TravelItinerary,
  TravelItineraryItem,
} from '../../core/models/itinerary.models';
import { ItineraryService } from '../../core/services/itinerary.service';
import { extractApiErrorMessage } from '../../core/utils/api-error.util';
import { LoadingSpinnerComponent } from '../../shared/components/loading-spinner/loading-spinner.component';

@Component({
  selector: 'app-itinerary-detail',
  imports: [
    CurrencyPipe,
    DatePipe,
    RouterLink,
    MatButtonModule,
    MatCardModule,
    MatIconModule,
    LoadingSpinnerComponent,
  ],
  template: `
    @if (loading()) {
      <app-loading-spinner message="Loading itinerary..." />
    } @else if (error()) {
      <p class="error">{{ error() }}</p>
      <a mat-button routerLink="/itineraries">Back to my trips</a>
    } @else if (itinerary(); as plan) {
      <div class="header-row">
        <a mat-button routerLink="/itineraries">
          <mat-icon>arrow_back</mat-icon>
          My trips
        </a>
      </div>

      <header class="page-header">
        <h1>{{ plan.title }}</h1>
        <p class="destination">
          {{ plan.destination.name }} · {{ plan.destination.city }}, {{ plan.destination.country }}
        </p>
        <p class="meta">
          {{ plan.durationDays }} day{{ plan.durationDays === 1 ? '' : 's' }}
          · Created {{ plan.createdAt | date: 'medium' }}
        </p>
        <a
          mat-stroked-button
          color="primary"
          [routerLink]="['/destinations', plan.destination.id]"
        >
          <mat-icon>place</mat-icon>
          View destination map
        </a>
      </header>

      <p class="disclaimer">
        This itinerary is generated by AI from the attractions and activities stored in our catalog.
        Treat it as inspiration: opening hours, availability and prices can change, so please verify
        details before you travel or book.
      </p>

      <div class="days">
        @for (day of plan.days; track day.dayNumber) {
          <mat-card class="day-card">
            <mat-card-header>
              <div class="day-badge">Day {{ day.dayNumber }}</div>
              <mat-card-title>{{ day.title }}</mat-card-title>
              @if (day.summary) {
                <mat-card-subtitle>{{ day.summary }}</mat-card-subtitle>
              }
            </mat-card-header>
            <mat-card-content>
              @if (!day.items.length) {
                <p class="muted">No planned items for this day.</p>
              } @else {
                <ol class="timeline">
                  @for (item of day.items; track item.order) {
                    <li class="timeline-item">
                      <div class="timeline-marker"></div>
                      <div class="item-body">
                        <div class="item-head">
                          <span class="time-of-day">{{ item.timeOfDay }}</span>
                          <span class="badge" [class]="badgeClass(item)">
                            {{ badgeLabel(item) }}
                          </span>
                        </div>
                        <h3>{{ item.title }}</h3>
                        @if (item.location) {
                          <p class="location">
                            <mat-icon class="inline-icon">place</mat-icon>
                            {{ item.location }}
                          </p>
                        }
                        @if (item.description) {
                          <p class="description">{{ item.description }}</p>
                        }
                        @if (item.activityPrice != null) {
                          <p class="price">
                            <strong>{{
                              item.activityPrice
                                | currency: (item.activityCurrency || 'EUR') : 'symbol' : '1.0-2'
                            }}</strong>
                            <span class="price-note">
                              Price from our activity catalog; not a live booking price.
                            </span>
                          </p>
                        }
                      </div>
                    </li>
                  }
                </ol>
              }
            </mat-card-content>
          </mat-card>
        }
      </div>
    }
  `,
  styles: `
    :host {
      display: block;
      width: min(880px, 100%);
      margin: 0 auto;
      padding: 1.5rem 1rem 2.5rem;
      box-sizing: border-box;
    }

    .header-row {
      margin-bottom: 0.5rem;
    }

    h1 {
      font-family: 'Fraunces', Georgia, serif;
      margin: 0 0 0.35rem;
      color: #0d4f52;
    }

    .destination {
      margin: 0;
      font-weight: 500;
    }

    .meta {
      margin: 0.2rem 0 0.75rem;
      color: var(--mat-sys-on-surface-variant);
      font-size: 0.9rem;
    }

    .disclaimer {
      margin: 1rem 0 1.5rem;
      padding: 0.75rem 1rem;
      border-radius: 8px;
      background: rgba(13, 115, 119, 0.06);
      color: var(--mat-sys-on-surface-variant);
      font-size: 0.875rem;
      line-height: 1.55;
    }

    .days {
      display: flex;
      flex-direction: column;
      gap: 1.25rem;
    }

    .day-card {
      overflow: hidden;
    }

    .day-badge {
      display: inline-block;
      background: #0d7377;
      color: #fff;
      font-size: 0.75rem;
      font-weight: 600;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      padding: 0.3rem 0.65rem;
      border-radius: 999px;
      margin-bottom: 0.5rem;
    }

    mat-card-title {
      font-family: 'Fraunces', Georgia, serif;
      font-size: 1.15rem;
    }

    .timeline {
      list-style: none;
      margin: 0;
      padding: 0;
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .timeline-item {
      display: grid;
      grid-template-columns: 14px 1fr;
      gap: 0.75rem;
      align-items: start;
    }

    .timeline-marker {
      width: 10px;
      height: 10px;
      margin-top: 0.45rem;
      border-radius: 50%;
      background: #2a9d8f;
      box-shadow: 0 0 0 3px rgba(42, 157, 143, 0.18);
    }

    .item-head {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 0.5rem;
    }

    .time-of-day {
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      color: var(--mat-sys-on-surface-variant);
      font-weight: 600;
    }

    .badge {
      font-size: 0.7rem;
      font-weight: 600;
      padding: 0.2rem 0.5rem;
      border-radius: 999px;
      background: rgba(0, 0, 0, 0.06);
    }

    .badge.attraction {
      background: rgba(13, 115, 119, 0.14);
      color: #0d4f52;
    }

    .badge.activity {
      background: rgba(233, 196, 106, 0.28);
      color: #6b4f14;
    }

    h3 {
      margin: 0.2rem 0 0.25rem;
      font-size: 1rem;
    }

    .location,
    .description,
    .price {
      margin: 0.15rem 0 0;
      font-size: 0.9rem;
      line-height: 1.5;
    }

    .location {
      display: flex;
      align-items: center;
      gap: 0.25rem;
      color: var(--mat-sys-on-surface-variant);
    }

    .inline-icon {
      font-size: 1rem;
      width: 1rem;
      height: 1rem;
    }

    .price-note {
      display: block;
      font-size: 0.75rem;
      color: var(--mat-sys-on-surface-variant);
    }

    .muted {
      color: var(--mat-sys-on-surface-variant);
    }

    .error {
      color: var(--mat-sys-error);
    }

    @media (max-width: 640px) {
      .timeline-item {
        grid-template-columns: 10px 1fr;
      }
    }
  `,
})
export class ItineraryDetailComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly itineraryService = inject(ItineraryService);

  readonly itinerary = signal<TravelItinerary | null>(null);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  constructor() {
    this.route.paramMap
      .pipe(
        switchMap((params) => {
          this.loading.set(true);
          this.error.set(null);

          const id = Number(params.get('id'));
          if (!Number.isFinite(id)) {
            this.error.set('Invalid itinerary id.');
            this.loading.set(false);
            return EMPTY;
          }

          return this.itineraryService.getById(id);
        }),
        takeUntilDestroyed()
      )
      .subscribe({
        next: (plan) => {
          this.itinerary.set(plan);
          this.loading.set(false);
        },
        error: (err) => {
          this.error.set(extractApiErrorMessage(err, 'Itinerary not found.'));
          this.loading.set(false);
        },
      });
  }

  badgeLabel(item: TravelItineraryItem): string {
    switch (item.itemType) {
      case 'Attraction':
        return 'Attraction';
      case 'Activity':
        return 'Activity';
      default:
        return 'Suggestion';
    }
  }

  badgeClass(item: TravelItineraryItem): string {
    switch (item.itemType) {
      case 'Attraction':
        return 'attraction';
      case 'Activity':
        return 'activity';
      default:
        return 'general';
    }
  }
}
